### ISSUE TITLE
Dependency issues while starting project...

### ISSUE THREAD

**Issue by mjosh1982** [BradPrit09/Quora-Demo#10]
While running the project , facing an issue with dependencies
UnsatisfiedDependencyException - 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration'
Please check and help.

**Comment by GowtamSagarP** [comment]
The issue happened because the driver jar file called postgresql-42.2.5.jar was not available.
Once, that was downloaded and added to classpath, the application will take this driver for connecting to database.
You can downnload the postgresql jar from this location.
Request you to close this comment, if the issue has got resolved.

Also, you have to make sure to install the maven environment on your OS as well.

**Comment by mjosh1982** [comment]
Thanks this solution worked.
